apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course-container
          image: studioghibli06/courses:25
          ports:
            - containerPort: 8888
          env:
            - name: MYSQL_HOST
              value: mysql   # MySQL service name within the Kubernetes cluster
            - name: MYSQL_PORT
              value: "3306"  # Default MySQL port
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
