apiVersion: v1
kind: Service
metadata:
  name: enrollment-service
spec:
  selector:
    app: enrollment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8883
      nodePort: 32606
  type: LoadBalancer