apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment
  template:
    metadata:
      labels:
        app: enrollment
    spec:
      containers:
        - name: enrollment-container
          image: studioghibli06/enrollment:15  # Update with your Docker Hub image
          ports:
            - containerPort: 8883
          env:
            - name: MYSQL_HOST
              value: mysql-service   # MySQL service name within the Kubernetes cluster
            - name: MYSQL_PORT
              value: "3306"  # Default MySQL port
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password