apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: studioghibli06/gateway:17
          ports:
            - containerPort: 8880
          env:
            - name: MYSQL_HOST
              value: mysql-service   # MySQL service name within the Kubernetes cluster
            - name: MYSQL_PORT
              value: "3306"  # Default MySQL port
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password