apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: studioghibli06/users:16
          ports:
            - containerPort: 8881
          env:
            - name: MYSQL_HOST
              value: mysql-service   # MySQL service name within the Kubernetes cluster
            - name: MYSQL_PORT
              value: "3306"  # Default MySQL port
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password